version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: spacy
    versions:
    - 2.3.5
    - 3.0.0
    - 3.0.1
    - 3.0.3
    - 3.0.4
    - 3.0.5
